# --- COMA specific parameters ---

action_selector: "multinomial"
epsilon_start: 1.0
epsilon_finish: .01
epsilon_anneal_time: 5000
mask_before_softmax: False

runner: "parallel"

buffer_size: 2
batch_size_run: 2
batch_size: 2

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval: 16

lr: 0.0005
critic_lr: 0.0005
td_lambda: 0.8

# use COMA
agent_output_type: "pi_logits"
learner: "coma_learner"
critic_q_fn: "coma"
critic_baseline_fn: "coma"
critic_train_mode: "seq"
critic_train_reps: 1
critic_mlp_layer_size: 64
q_nstep: 0  # 0 corresponds to default Q, 1 is r + gamma*Q, etc

name: "coma"
